name: code style workflow
on: [push]

jobs: 
  hadolint:
    name: Dockerfiles linter 
    runs-on: ubuntu-latest
    steps:
      - name: copy resources
        uses: actions/checkout@v2
      - name: install docker
        run: curl -sSL https://get.docker.com | sh
      - name: launch Hadolint 
        run: docker run --rm -i hadolint/hadolint < Dockerfile

  phpcsfixer:
    name: php cs fixer job 
    runs-on: ubuntu-latest
    steps:
      - name: copy resources
        uses: actions/checkout@v2
      - name: install php cs fixer 
        run: |
          curl -L https://cs.symfony.com/download/php-cs-fixer-v2.phar -o php-cs-fixer 
          sudo chmod a+x php-cs-fixer
          sudo mv php-cs-fixer /usr/local/bin/php-cs-fixer
      - name: validate code source 
        run: php-cs-fixer fix --dry-run src
  
  security-checker:
    name: check security 
    runs-on: ubuntu-latest
    steps:
      - name:
        uses: actions/checkout@v2
      - name: install sensiolabs security checker
        run: |
          curl -L https://get.sensiolabs.org/security-checker.phar -o security-checker
          sudo chmod a+x security-checker
      - name: launch security checker
        run: php security-checker security:check symfony.lock
